### ISSUE TITLE
Argument `dataset_version` is invalid for IGLUDataset.

### ISSUE THREAD

**Issue by MarcCote** [iglu-contest/gridworld#7]
Running the main branch of this repo, I've encountered an issue with one of the code snippets from [Overview.md](https://gitlab.aicrowd.com/aicrowd/challenges/iglu-challenge-2022/iglu-2022-challenge-checklist/-/blob/master/Overview.md). 

```python
import gym
from gridworld.data import IGLUDataset

dataset = IGLUDataset(dataset_version='v0.1.0-rc1') 
# leave dataset_version empty to access the most recent version of the dataset.

env = gym.make('IGLUGridworld-v0')
env.set_task_generator(dataset)
```
Argument `dataset_version` is invalid for IGLUDataset.

**Comment by artemZholus** [comment]
fixed
