### ISSUE TITLE
Library 'requests' is missing from requirements.txt

### ISSUE THREAD

**Issue by MarcCote** [iglu-contest/gridworld#8]
Running the main branch of this repo, I've encountered an issue with one of the code snippets from [Overview.md](https://gitlab.aicrowd.com/aicrowd/challenges/iglu-challenge-2022/iglu-2022-challenge-checklist/-/blob/master/Overview.md). 

In `data/load.py`, to download the dataset, the `requests` library is needed.

**Comment by artemZholus** [comment]
fixed
